apiVersion: v1
kind: Namespace
metadata:
  name: teastore

---
apiVersion: v1
kind: Service
metadata:
  name: teastore-db
  namespace: teastore
  labels:
    app: teastore
    run: teastore-db
spec:
  ports:
  - port: 3306
    protocol: TCP
  selector:
    run: teastore-db
---
apiVersion: v1
kind: Service
metadata:
  name: teastore-registry
  namespace: teastore
  labels:
    app: teastore
    run: teastore-registry
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    run: teastore-registry
---
apiVersion: v1
kind: Service
metadata:
  name: teastore-webui
  namespace: teastore
  labels:
    app: teastore
    run: teastore-webui
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 30080
    protocol: TCP
  selector:
    run: teastore-webui
