# Registry and repository for Docker images
# Default is docker/robotshop/image:latest
image:
  repo: robotshop
  version: latest
  pullPolicy: IfNotPresent

# EUM configuration
# Provide your key and set the endpoint
eum:
  key: null
  url: https://eum-eu-west-1.instana.io
  #url: https://eum-us-west-2.instana.io

# Pod Security Policy
psp:
  enabled: false

# For the mini ones minikube, minishift set to true
nodeport: false

# "special" Openshift. Set to true when deploying to any openshift flavour
openshift: false

ocCreateRoute: false

######################################
# Affinities for individual workloads
# set in the following way:
# <workload>:
#   affinity: {}
#   nodeSelector: {}
#   tolerations: []
#   labels:{}
######################################

cart:
  labels:
    app: robot-shop
  nodeSelector:
    name: worker2      

catalogue:
  labels:
    app: robot-shop
  nodeSelector:  
    name: worker2

dispatch:
  labels:
    app: robot-shop
  nodeSelector:
    name: worker

mongodb:
  labels:
    app: robot-shop
  nodeSelector:
    name: worker2

mysql:
  labels:
    app: robot-shop
  nodeSelector:
    name: worker2

payment:
  labels:
    app: robot-shop
  # Alternative payment gateway URL
  # Default is https://www.paypal.com
  gateway: null
  #gateway: https://www.worldpay.com
  nodeSelector:
    name: worker2

rabbitmq:
  labels:
    app: robot-shop
  nodeSelector:  
    name: worker2

ratings:
  labels:
    app: robot-shop
  nodeSelector:
    name: worker

redis:
  labels:
    app: robot-shop      
  # Storage class to use with redis statefulset.
  storageClassName: local-path
  nodeSelector:
    name: worker

shipping:
  labels:
    app: robot-shop
  nodeSelector:
    name: worker

user:
  labels:
    app: robot-shop
  nodeSelector:
    name: worker

web:
  labels:
    app: robot-shop
  nodeSelector:
    name: worker
