# Registry and repository for Docker images
# Default is docker/robotshop/image:latest
image:
  repo: robotshop
  version: latest
  pullPolicy: IfNotPresent

# EUM configuration
# Provide your key and set the endpoint
eum:
  key: null
  url: https://eum-eu-west-1.instana.io
  #url: https://eum-us-west-2.instana.io

# Pod Security Policy
psp:
  enabled: false

# For the mini ones minikube, minishift set to true
nodeport: false

# "special" Openshift. Set to true when deploying to any openshift flavour
openshift: false

ocCreateRoute: false

######################################
# Affinities for individual workloads
# set in the following way:
# <workload>:
#   affinity: {}
#   nodeSelector: {}
#   tolerations: []
#   labels:{}
######################################

cart:
  labels:
    app: robot-shop

catalogue:
  labels:
    app: robot-shop

dispatch:
  labels:
    app: robot-shop

mongodb:
  labels:
    app: robot-shop

mysql:
  labels:
    app: robot-shop

payment:
  labels:
    app: robot-shop
  # Alternative payment gateway URL
  # Default is https://www.paypal.com
  gateway: null
  #gateway: https://www.worldpay.com

rabbitmq:
  labels:
    app: robot-shop

ratings:
  labels:
    app: robot-shop

redis:
  labels:
    app: robot-shop      
  # Storage class to use with redis statefulset.
  storageClassName: local-path

shipping:
  labels:
    app: robot-shop

user:
  labels:
    app: robot-shop

web:
  labels:
    app: robot-shop
