apiVersion: v1
kind: Service
metadata:
  name: cart
  labels:
    service: cart
    {{- with .Values.cart.labels }}
    {{ toYaml . | nindent 4 }}
    {{- end }}
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    service: cart
    {{- with .Values.cart.labels }}
    {{ toYaml . | nindent 4 }}
    {{- end }}

