apiVersion: v1
kind: Service
metadata:
  name: catalogue
  labels:
    service: catalogue
    {{- with .Values.catalogue.labels }}
    {{ toYaml . | nindent 4 }}
    {{- end }}
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    service: catalogue
    {{- with .Values.catalogue.labels }}
    {{ toYaml . | nindent 4 }}
    {{- end }}

