{{ if .Values.psp.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: robot-shop
  labels:
    {{- with .Values.labels }}
    {{ toYaml . | nindent 4 }}
    {{- end }}
rules:
- apiGroups:
  - policy
  resourceNames:
  - robot-shop
  resources:
  - podsecuritypolicies
  verbs:
  - use
{{ end }}

