# dispatch just listens to a message queue
# it does not expose any ports
apiVersion: v1
kind: Service
metadata:
  name: dispatch
  labels:
    service: dispatch
    {{- with .Values.dispatch.labels }}
    {{ toYaml . | nindent 4 }}
    {{- end }}
spec:
  clusterIP: None
  ports:
  - name: headless
    port: 55555
    targetPort: 0
  selector:
    service: dispatch
    {{- with .Values.dispatch.labels }}
    {{ toYaml . | nindent 4 }}
    {{- end }}

