apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
    service: mongodb
    {{- with .Values.mongodb.labels }}
    {{ toYaml . | nindent 4 }}
    {{- end }}
spec:
  ports:
  - name: mongo
    port: 27017
    targetPort: 27017
  selector:
    service: mongodb
    {{- with .Values.mongodb.labels }}
    {{ toYaml . | nindent 4 }}
    {{- end }}

