apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    service: mysql
    {{- with .Values.mysql.labels }}
    {{ toYaml . | nindent 4 }}
    {{- end }}
spec:
  ports:
  - name: mysql
    port: 3306
    targetPort: 3306
  selector:
    service: mysql
    {{- with .Values.mysql.labels }}
    {{ toYaml . | nindent 4 }}
    {{- end }}

