apiVersion: v1
kind: Service
metadata:
  name: payment
  labels:
    service: payment
    {{- with .Values.payment.labels }}
    {{ toYaml . | nindent 4 }}
    {{- end }}
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    service: payment
    {{- with .Values.payment.labels }}
    {{ toYaml . | nindent 4 }}
    {{- end }}

