apiVersion: v1
kind: Service
metadata:
  name: ratings
  labels:
    service: ratings
    {{- with .Values.ratings.labels }}
    {{ toYaml . | nindent 4 }}
    {{- end }}
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    service: ratings
    {{- with .Values.ratings.labels }}
    {{ toYaml . | nindent 4 }}
    {{- end }}

