apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    service: redis
    {{- with .Values.redis.labels }}
    {{ toYaml . | nindent 4 }}
    {{- end }}
spec:
  ports:
  - name: redis
    port: 6379
    targetPort: 6379
  selector:
    service: redis
    {{- with .Values.redis.labels }}
    {{ toYaml . | nindent 4 }}
    {{- end }}

