{{ if .Values.psp.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: robot-shop
  namespace: robot-shop
  labels:
    {{- with .Values.labels }}
    {{ toYaml . | nindent 4 }}
    {{- end }}
{{ end }}

