apiVersion: v1
kind: Service
metadata:
  name: shipping
  labels:
    service: shipping
    {{- with .Values.shipping.labels }}
    {{ toYaml . | nindent 4 }}
    {{- end }}
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    service: shipping
    {{- with .Values.shipping.labels }}
    {{ toYaml . | nindent 4 }}
    {{- end }}

