apiVersion: apps/v1
kind: Deployment
metadata:
  name: teastore-db
  namespace: teastore
  labels:
    app: teastore
    run: teastore-db
spec:
  selector:
    matchLabels:
      app: teastore
      run: teastore-db
  template:
    metadata:
      labels:
        app: teastore
        run: teastore-db
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
    spec:
      containers:
      - name: teastore-db
        image: descartesresearch/teastore-db
        ports:
        - containerPort: 3306
        resources:
          requests:
            memory: "256Mi"
          limits:
            memory: "512Mi"
        securityContext:
          capabilities:
            add: ["NET_RAW"]
      nodeSelector:
        name: "worker2"      
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: teastore-registry
  namespace: teastore
  labels:
    app: teastore
    run: teastore-registry
spec:
  selector:
    matchLabels:
      app: teastore
      run: teastore-registry
  template:
    metadata:
      labels:
        app: teastore
        run: teastore-registry
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"        
    spec:
      containers:
      - name: teastore-registry
        image: descartesresearch/teastore-registry
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "256Mi"
          limits:
            memory: "512Mi"
        env:
        - name: USE_POD_IP
          value: "true"
        securityContext:
          capabilities:
            add: ["NET_RAW"] 
      nodeSelector:
        name: "worker"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: teastore-persistence
  namespace: teastore
  labels:
    app: teastore
    run: teastore-persistence
spec:
  selector:
    matchLabels:
      app: teastore
      run: teastore-persistence
  template:
    metadata:
      labels:
        app: teastore
        run: teastore-persistence
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
    spec:
      containers:
      - name: teastore-persistence
        image: descartesresearch/teastore-persistence
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "256Mi"
          limits:
            memory: "512Mi"
        env:
        - name: USE_POD_IP
          value: "true"
        - name: REGISTRY_HOST
          value: "teastore-registry"
        - name: DB_HOST
          value: "teastore-db"
        - name: DB_PORT
          value: "3306"
        securityContext:
          capabilities:
            add: ["NET_RAW"]            
      nodeSelector:
        name: "worker"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: teastore-auth
  namespace: teastore
  labels:
    app: teastore
    run: teastore-auth
spec:
  selector:
    matchLabels:
      app: teastore
      run: teastore-auth
  template:
    metadata:
      labels:
        app: teastore
        run: teastore-auth
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
    spec:
      containers:
      - name: teastore-auth
        image: descartesresearch/teastore-auth
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "256Mi"
          limits:
            memory: "512Mi"
        env:
        - name: USE_POD_IP
          value: "true"
        - name: REGISTRY_HOST
          value: "teastore-registry"
        securityContext:
          capabilities:
            add: ["NET_RAW"]
      nodeSelector:
        name: "worker2"    

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: teastore-image
  namespace: teastore
  labels:
    app: teastore
    run: teastore-image
spec:
  selector:
    matchLabels:
      app: teastore
      run: teastore-image
  template:
    metadata:
      labels:
        app: teastore
        run: teastore-image
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
    spec:
      containers:
      - name: teastore-image
        image: descartesresearch/teastore-image
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "256Mi"
          limits:
            memory: "512Mi"
        env:
        - name: USE_POD_IP
          value: "true"
        - name: REGISTRY_HOST
          value: "teastore-registry"
        securityContext:
          capabilities:
            add: ["NET_RAW"]
      nodeSelector:
        name: "worker"      
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: teastore-recommender
  namespace: teastore
  labels:
    app: teastore
    run: teastore-recommender
spec:
  selector:
    matchLabels:
      app: teastore
      run: teastore-recommender
  template:
    metadata:
      labels:
        app: teastore
        run: teastore-recommender
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
    spec:
      containers:
      - name: teastore-recommender
        image: descartesresearch/teastore-recommender
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "256Mi"
          limits:
            memory: "512Mi"
        env:
        - name: USE_POD_IP
          value: "true"
        - name: REGISTRY_HOST
          value: "teastore-registry"
        securityContext:
          capabilities:
            add: ["NET_RAW"]
      nodeSelector:
        name: "worker2"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: teastore-webui
  namespace: teastore
  labels:
    app: teastore
    run: teastore-webui
spec:
  selector:
    matchLabels:
      app: teastore
      run: teastore-webui
  template:
    metadata:
      labels:
        app: teastore
        run: teastore-webui
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
    spec:
      containers:
      - name: teastore-webui
        image: rony0718/my-custom-teastore-webui8
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "256Mi"
          limits:
            memory: "512Mi"
        env:
        - name: USE_POD_IP
          value: "true"
        - name: REGISTRY_HOST
          value: "teastore-registry"
        securityContext:
          capabilities:
            add: ["NET_RAW"]
      nodeSelector:
        name: "worker"
